name: udevs
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-220.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  zoom_tap_animation: ^1.1.0
  dio: ^5.3.3
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  path: ^1.8.3
  lottie: ^2.6.0
  mask_text_input_formatter: ^2.5.0
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/svg/


#   example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
